# Generated by Django 6.0.4 on 2026-05-07 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REQUESTS', 'Requests'), ('SET PIN', 'Set PIN'), ('OTHER TRANSACTIONS', 'Other Transactions')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='main-services/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('device_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, help_text='e.g. Teller Counter 1', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='configuration.branch')),
            ],
            options={
                'ordering': ['branch', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(choices=[('CASH DEPOSIT', 'Cash Deposit'), ('CHEQUE DEPOSIT', 'Cheque Deposit'), ('EZWICH CARD DEPOSIT', 'EZWICHCard Deposit'), ('MOBILE MONEY DEPOSIT', 'Mobile Money Deposit'), ('CASH WITHDRAWAL', 'Cash Withdrawal (Own Account)'), ('CHEQUE WITHDRAWAL', 'Cheque Withdrawal (Third Party)'), ('FOREIGN TO LOCAL', 'Foreign to Local Currency (Third Party)'), ('EZWICH CARD WITHDRAWAL', 'EZWICHCard Withdrawal'), ('MOBILE MONEY WITHDRAWAL', 'Mobile Money Withdrawal'), ('FOREX PURCHASE', 'Forex Purchase'), ('FUNDS TRANSFER', 'Funds Transfer'), ('GHIPPS INSTANT PAY', 'GHIPPS Instant Pay (GIP)'), ('STATEMENT REQUEST', 'Statement Request'), ('CHEQUE BOOK REQUEST', 'Cheque Book Request'), ('BALANCE ENQUIRY', 'Balance Enquiry Request'), ('BANKERS DRAFT REQUEST', 'Bankers Draft Request'), ('STOP CHEQUE', 'Stop Cheque'), ('STANDING ORDER', 'Standing Order'), ('SIGNUP', 'SignUp'), ('FORGOT PIN', 'Forgot PIN'), ('ACTIVATE PIN', 'Activate PIN')], max_length=50, unique=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='services/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='configuration.mainservice')),
            ],
        ),
        migrations.CreateModel(
            name='BranchWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='configuration.branch')),
            ],
            options={
                'verbose_name_plural': 'branch working hours',
                'ordering': ['day'],
                'unique_together': {('branch', 'day')},
            },
        ),
    ]
