# Generated by Django 6.0.4 on 2026-05-11 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('counter_code', models.CharField(max_length=20)),
                ('counter_name', models.CharField(max_length=100)),
                ('counter_type', models.CharField(choices=[('PRIORITY_QUEUE', 'Priority Queue'), ('NON_PRIORITY_QUEUE', 'Non-priority Queue'), ('VIP_QUEUE', 'VIP Queue')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_backoffice', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='configuration.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters_created', to=settings.AUTH_USER_MODEL)),
                ('operations', models.ManyToManyField(blank=True, related_name='counters', to='configuration.service')),
            ],
            options={
                'ordering': ['branch', 'counter_name'],
            },
        ),
    ]
