# Generated by Django 6.0.4 on 2026-05-14 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_counter'),
        ('core', '0002_ticket_and_deposit_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='current_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_at_counter', to='core.ticket'),
        ),
    ]
