# Generated by Django 6.0.4 on 2026-05-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_counter_current_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemVoiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('EDGE_TTS', 'Edge TTS (Microsoft Neural)'), ('GTTS', 'gTTS (Google)')], default='EDGE_TTS', max_length=20)),
                ('voice', models.CharField(default='en-US-GuyNeural', max_length=100)),
                ('rate', models.CharField(default='+0%', help_text='Edge TTS speed, e.g. -20%, +0%, +20%', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('tld', models.CharField(default='com', max_length=20)),
                ('slow', models.BooleanField(default=False)),
                ('announcement_template', models.TextField(default='Ticket number {ticket_number}, please proceed to {counter_name}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Voice Configuration',
            },
        ),
        migrations.CreateModel(
            name='BranchTVConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_texts', models.JSONField(default=list)),
                ('show_ads', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tv_config', to='configuration.branch')),
            ],
            options={
                'verbose_name': 'Branch TV Configuration',
            },
        ),
        migrations.CreateModel(
            name='BranchVoiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('EDGE_TTS', 'Edge TTS (Microsoft Neural)'), ('GTTS', 'gTTS (Google)')], default='EDGE_TTS', max_length=20)),
                ('voice', models.CharField(default='en-US-GuyNeural', max_length=100)),
                ('rate', models.CharField(default='+0%', help_text='Edge TTS speed, e.g. -20%, +0%, +20%', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('tld', models.CharField(default='com', max_length=20)),
                ('slow', models.BooleanField(default=False)),
                ('announcement_template', models.TextField(default='Ticket number {ticket_number}, please proceed to {counter_name}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_config', to='configuration.branch')),
            ],
            options={
                'verbose_name': 'Branch Voice Configuration',
            },
        ),
        migrations.CreateModel(
            name='TVAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image')], max_length=10)),
                ('file', models.FileField(upload_to='tv_ads/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tv_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='configuration.branchtvconfig')),
            ],
            options={
                'verbose_name': 'TV Advertisement',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
