# Generated by Django 6.0.4 on 2026-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_remove_service_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainservice',
            name='name',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REQUESTS', 'Requests'), ('SET PIN', 'Set PIN'), ('OTHER TRANSACTIONS', 'Other Transactions')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('CASH DEPOSIT', 'Cash Deposit'), ('CHEQUE DEPOSIT', 'Cheque Deposit'), ('EZWICH CARD DEPOSIT', 'EZWICHCard Deposit'), ('MOBILE MONEY DEPOSIT', 'Mobile Money Deposit'), ('CASH WITHDRAWAL', 'Cash Withdrawal (Own Account)'), ('CHEQUE WITHDRAWAL', 'Cheque Withdrawal (Third Party)'), ('FOREIGN TO LOCAL', 'Foreign to Local Currency (Third Party)'), ('EZWICH CARD WITHDRAWAL', 'EZWICHCard Withdrawal'), ('MOBILE MONEY WITHDRAWAL', 'Mobile Money Withdrawal'), ('FOREX PURCHASE', 'Forex Purchase'), ('FUNDS TRANSFER', 'Funds Transfer'), ('GHIPPS INSTANT PAY', 'GHIPPS Instant Pay (GIP)'), ('STATEMENT REQUEST', 'Statement Request'), ('CHEQUE BOOK REQUEST', 'Cheque Book Request'), ('BALANCE ENQUIRY', 'Balance Enquiry Request'), ('BANKERS DRAFT REQUEST', 'Bankers Draft Request'), ('STOP CHEQUE', 'Stop Cheque'), ('STANDING ORDER', 'Standing Order'), ('SIGNUP', 'SignUp'), ('FORGOT PIN', 'Forgot PIN'), ('ACTIVATE PIN', 'Activate PIN')], max_length=50, unique=True),
        ),
    ]
