# Generated by Django 6.0.4 on 2026-06-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_otherbank_otherbankbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='prefix',
            field=models.CharField(blank=True, default='', help_text='Ticket number prefix for this service', max_length=6),
        ),
    ]
