# Generated by Django 6.0.4 on 2026-05-14 16:31

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_counter_current_ticket'),
        ('core', '0002_ticket_and_deposit_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticketservice',
            name='core_ticketservice_ticket_position_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='core_ticket_branch_ticket_number_uniq',
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_deposits_served', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='t24_reference',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='t24_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='t24_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMMITTED', 'Committed'), ('FAILED_COMMIT', 'Failed Commit')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_deposits_served', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='t24_reference',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='t24_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='t24_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMMITTED', 'Committed'), ('FAILED_COMMIT', 'Failed Commit')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='ezwichdeposit',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ezwich_deposits_served', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ezwichdeposit',
            name='t24_reference',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ezwichdeposit',
            name='t24_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ezwichdeposit',
            name='t24_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMMITTED', 'Committed'), ('FAILED_COMMIT', 'Failed Commit')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_money_deposits_served', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='t24_reference',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='t24_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='t24_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMMITTED', 'Committed'), ('FAILED_COMMIT', 'Failed Commit')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='processed_services_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of services that have had their model object created.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='servced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_served', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='services_data',
            field=models.JSONField(default=list, help_text='Raw services payload submitted at ticket creation time.'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['branch', 'created_at'], name='ticket_branch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'created_at'], name='ticket_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['servced_by', 'status'], name='ticket_teller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['services_data'], name='ticket_services_data_gin_idx'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='hold_reason',
        ),
        migrations.DeleteModel(
            name='TicketService',
        ),
    ]
