# Generated by Django 6.0.4 on 2026-05-17 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ticketservice_core_ticketservice_ticket_position_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hold_started_at',
            field=models.DateTimeField(blank=True, help_text='When the current hold period started.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_hold_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Total accumulated hold time in seconds across all holds.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='verification_data',
            field=models.JSONField(blank=True, help_text='Ghana Card / NIA verification result linked at ticket creation.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('ON_GOING', 'On going'), ('ON_HOLD', 'On hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], db_index=True, default='WAITING', max_length=20),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('card_number', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='verification_faces/')),
                ('verified', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, help_text='Raw response payload from the NIA API.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['card_number', 'created_at'], name='verification_card_date_idx')],
            },
        ),
    ]
