# Generated by Django 6.0.4 on 2026-06-03 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_alter_service_prefix'),
        ('core', '0004_ticket_hold_started_at_ticket_total_hold_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Kiosk / device that issued the ticket. Null for mobile check-in.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to='configuration.device'),
        ),
    ]
