# Generated by Django 6.0.4 on 2026-05-11 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("configuration", "0002_counter"),
    ]

    operations = [
        # Drop stale tables left by the previous 0002 migration
        # (accounts_userapproval had FK → accounts_systemuser, so drop in order)
        migrations.RunSQL(
            sql="""
                DELETE FROM django_migrations
                WHERE app = 'accounts' AND name = '0002_role_systemuser_userapproval';
                DROP TABLE IF EXISTS accounts_userapproval CASCADE;
                DROP TABLE IF EXISTS accounts_systemuser CASCADE;
                DROP TABLE IF EXISTS accounts_role CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="customuser",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="configuration.branch",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cbs_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="queue_counter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="configuration.counter",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Permission group governing what this user can do.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_users",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="t24_login_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="t24_username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "Admin"),
                    ("TELLER", "Teller"),
                    ("MANAGER", "Manager"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
